### ISSUE TITLE
Package (generic label) terraform for our static website deployment (s3/cloudfront/hsts/etc)

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/we_are_platform#1]
Due to the specific policy requirements pertaining to HTTPS and HSTS implementation, it's currently somewhat annoying to deploy a simple static website as most of the current offerings; github pages, netlify, etc, seem to be missing on one aspect or another.

Github doesn't offer HSTS, Netlify makes use of ciphers/protocols not currently recommended by CCCS.

This issue is to investigate packaging up the way we deploy digital&numerique.canada.ca to make it a one click 'webify!!!' to get a page from a static folder structure, onto the inter-webs.

Depending on level of interest, it may also be worth taking a quick peek at 18F's Federalist, which appears to be a github pages clone, to see if the level of effort would be worth the time.

**Comment by maxneuvians** [comment]
Terraform for a static site here: https://github.com/cds-snc/static-site-terraform. Attached is the domain scan output for a sample site.

[sample.txt](https://github.com/cds-snc/we_are_platform/files/3756810/sample.txt)

**Comment by obrien-j** [comment]
Looks good. I flipped it to a few people to test without any other context.  Feel free to close if you're happy with where it's at, or leave open, and update with any other follow-on work you think needs doing (docs/etc)
Once it's gold, we should put this up on the products page.
